### ISSUE TITLE
Tab key not working on shift field on create account page.

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Judith-Store-Dev#11]
Bug 1 - Tab key not working on shift field on create account page.
Exp - Tab key should work for shift on fields on create account page.
Ref Link -  https://drive.google.com/file/d/1cf6VWjtnj1tI5ao5iQAjw_y-VcjI25m9/view

Bug 2 - button UI issue on create account page.
Exp - Sign in button should show below create button.
Ref Link - https://nimb.ws/AazI2w

**Comment by devSharibAli** [comment]
fixed

**Comment by ankitcedcoss** [comment]
Bug Fixed
