### ISSUE TITLE
Out of stock product checkout issue

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Judith-Store-Dev#19]
Bug - User able to add out of stock product into cart and able to checkout.
Exp - User should not be able to add out of stock products into cart and cannot do checkouts with those product.
Ref link - https://drive.google.com/file/d/1Mtj1hYLQ_VlpFKnsAfmaAG87DJVIbHDz/view

**Comment by devSharibAli** [comment]
Not an issue as first available variant of the product is getting added, you can see that the variant of the product added to cart is available
![image](https://user-images.githubusercontent.com/100212678/163579817-69678409-4cb1-4a20-ba23-33eba77ca74c.png)
![image](https://user-images.githubusercontent.com/100212678/163579865-391459c6-2966-411d-b708-770aee13934c.png)

**Comment by devSharibAli** [comment]
Not an issue first available variant is getting added to cart
![image](https://user-images.githubusercontent.com/100212678/163583779-b3fe9687-13e9-43f3-af29-f20eb742cef0.png)
![image](https://user-images.githubusercontent.com/100212678/163583856-eff5ee52-86e8-44db-81ab-0bbb6f2f8ef9.png)

**Comment by devSharibAli** [comment]
![image](https://user-images.githubusercontent.com/100212678/163583942-04549ed3-566f-4084-87ad-2273fd63819e.png)

**Comment by ankitcedcoss** [comment]
Bug Closed
